In [1]:
import pandas as pd
import numpy as np

In [34]:
url='https://data.epa.gov.tw/api/v1/aqx_p_02?limit=1000&api_key=9be7b239-557b-4c10-9775-78cadfc555e9&format=csv'
data=pd.read_csv(url).dropna()
data

    Site county  PM25  DataCreationDate ItemUnit
0     前鎮    高雄市    49  2022-01-12 20:00    μg/m3
1     汐止    新北市    13  2022-01-12 20:00    μg/m3
2     萬里    新北市     5  2022-01-12 20:00    μg/m3
3     新店    新北市     9  2022-01-12 20:00    μg/m3
4     土城    新北市    10  2022-01-12 20:00    μg/m3
..   ...    ...   ...               ...      ...
101   楠梓    高雄市    53  2022-01-12 20:00    μg/m3
102   宜蘭    宜蘭縣     9  2022-01-12 20:00    μg/m3
103   中壢    桃園市    14  2022-01-12 20:00    μg/m3
104   竹山    南投縣    54  2022-01-12 20:00    μg/m3
105   復興    高雄市    44  2022-01-12 20:00    μg/m3

[106 rows x 5 columns]

In [47]:
data.groupby('county').mean().index.tolist()

['南投縣',
 '嘉義市',
 '嘉義縣',
 '基隆市',
 '宜蘭縣',
 '屏東縣',
 '彰化縣',
 '新北市',
 '新竹市',
 '新竹縣',
 '桃園市',
 '澎湖縣',
 '臺中市',
 '臺北市',
 '臺南市',
 '臺東縣',
 '花蓮縣',
 '苗栗縣',
 '連江縣',
 '金門縣',
 '雲林縣',
 '高雄市']

In [48]:
data.groupby('Site').mean().index.tolist()

['三義',
 '三重',
 '中壢',
 '中山',
 '二林',
 '仁武',
 '冬山',
 '前金',
 '前鎮',
 '南投',
 '古亭',
 '善化',
 '嘉義',
 '土城',
 '埔里',
 '基隆',
 '士林',
 '大同',
 '大園',
 '大城',
 '大寮',
 '大里',
 '安南',
 '宜蘭',
 '富貴角',
 '小港',
 '屏東',
 '崙背',
 '左營',
 '平鎮',
 '彰化',
 '復興',
 '忠明',
 '恆春',
 '斗六',
 '新店',
 '新港',
 '新營',
 '新竹',
 '新莊',
 '朴子',
 '松山',
 '板橋',
 '林口',
 '林園',
 '桃園',
 '楠梓',
 '橋頭',
 '永和',
 '汐止',
 '沙鹿',
 '淡水',
 '湖口',
 '潮州',
 '竹山',
 '竹東',
 '線西',
 '美濃',
 '臺南',
 '臺東',
 '臺西',
 '花蓮',
 '苗栗',
 '菜寮',
 '萬華',
 '萬里',
 '西屯',
 '觀音',
 '豐原',
 '金門',
 '關山',
 '陽明',
 '頭份',
 '馬公',
 '馬祖',
 '鳳山',
 '麥寮',
 '龍潭']

In [4]:
_sort='county'
_ascending = 'false'
_groupby='county'
_groupbycol=['臺北市','臺中市']

In [9]:
ascending = (_ascending == 'true')
print(f'sorted by {_sort}, ascending={ascending}')
data = data.sort_values(by=_sort, ascending=ascending)
data

sorted by county, ascending=False

    Site county  PM25  DataCreationDate ItemUnit
0     前鎮    高雄市  31.0  2022-01-12 19:00    μg/m3
20    前金    高雄市  37.0  2022-01-12 19:00    μg/m3
101   楠梓    高雄市  42.0  2022-01-12 19:00    μg/m3
75    左營    高雄市  45.0  2022-01-12 19:00    μg/m3
74    大寮    高雄市  43.0  2022-01-12 19:00    μg/m3
..   ...    ...   ...               ...      ...
18    南投    南投縣  60.0  2022-01-12 19:00    μg/m3
63    南投    南投縣  60.0  2022-01-12 19:00    μg/m3
82    埔里    南投縣  26.0  2022-01-12 19:00    μg/m3
104   竹山    南投縣  59.0  2022-01-12 19:00    μg/m3
46    埔里    南投縣  26.0  2022-01-12 19:00    μg/m3

[100 rows x 5 columns]

In [27]:
#表頭
a = data.columns
#數值
b = data.values
#更新時間
c = data['DataCreationDate'][0]; 
list(a),list(b),c

(['Site', 'county', 'PM25', 'DataCreationDate', 'ItemUnit'],
 [array(['前鎮', '高雄市', 31.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['前金', '高雄市', 37.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['楠梓', '高雄市', 42.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['左營', '高雄市', 45.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['大寮', '高雄市', 43.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['仁武', '高雄市', 45.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['小港', '高雄市', 34.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['林園', '高雄市', 39.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['橋頭', '高雄市', 50.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['左營', '高雄市', 45.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['大寮', '高雄市', 43.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['鳳山', '高雄市', 44.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['仁武', '高雄市', 45.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['復興', '高雄市', 28.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['美濃', '高雄市', 43.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['麥寮', '雲林縣', 18.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['斗六', '雲林縣', 51.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['臺西', '雲林縣', 16.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['臺西', '雲林縣', 16.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['崙背', '雲林縣', 30.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['斗六', '雲林縣', 51.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['崙背', '雲林縣', 30.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['金門', '金門縣', 32.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['金門', '金門縣', 32.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['金門', '金門縣', 32.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['馬祖', '連江縣', 39.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['三義', '苗栗縣', 15.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['苗栗', '苗栗縣', 14.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['頭份', '苗栗縣', 11.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['三義', '苗栗縣', 15.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['花蓮', '花蓮縣', 9.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['花蓮', '花蓮縣', 9.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['臺東', '臺東縣', 7.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['臺東', '臺東縣', 7.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['臺南', '臺南市', 22.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['安南', '臺南市', 26.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['臺南', '臺南市', 22.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['新營', '臺南市', 27.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['安南', '臺南市', 26.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['善化', '臺南市', 51.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['士林', '臺北市', 11.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['陽明', '臺北市', 6.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['松山', '臺北市', 14.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['萬華', '臺北市', 10.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['古亭', '臺北市', 13.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['大同', '臺北市', 15.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['中山', '臺北市', 12.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['忠明', '臺中市', 19.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['西屯', '臺中市', 17.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['西屯', '臺中市', 17.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['大里', '臺中市', 17.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['沙鹿', '臺中市', 18.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['豐原', '臺中市', 17.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['馬公', '澎湖縣', 10.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['馬公', '澎湖縣', 10.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['馬公', '澎湖縣', 10.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['桃園', '桃園市', 11.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['觀音', '桃園市', 10.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['平鎮', '桃園市', 16.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['中壢', '桃園市', 11.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['大園', '桃園市', 9.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['龍潭', '桃園市', 12.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['竹東', '新竹縣', 13.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['湖口', '新竹縣', 10.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['新竹', '新竹市', 16.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['林口', '新北市', 13.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['萬里', '新北市', 5.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['菜寮', '新北市', 11.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['永和', '新北市', 15.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['板橋', '新北市', 11.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['淡水', '新北市', 8.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['永和', '新北市', 15.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['汐止', '新北市', 10.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['三重', '新北市', 14.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['新莊', '新北市', 10.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['新店', '新北市', 10.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['土城', '新北市', 10.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['富貴角', '新北市', 9.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['彰化', '彰化縣', 17.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['線西', '彰化縣', 21.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['彰化', '彰化縣', 17.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['大城', '彰化縣', 16.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['潮州', '屏東縣', 26.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['屏東', '屏東縣', 33.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['潮州', '屏東縣', 26.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['恆春', '屏東縣', 4.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['屏東', '屏東縣', 33.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['宜蘭', '宜蘭縣', 12.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['冬山', '宜蘭縣', 8.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['冬山', '宜蘭縣', 8.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['冬山', '宜蘭縣', 8.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['基隆', '基隆市', 9.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['朴子', '嘉義縣', 24.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['新港', '嘉義縣', 21.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['嘉義', '嘉義市', 54.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['南投', '南投縣', 60.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['南投', '南投縣', 60.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['埔里', '南投縣', 26.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['竹山', '南投縣', 59.0, '2022-01-12 19:00', 'μg/m3'], dtype=object),
  array(['埔里', '南投縣', 26.0, '2022-01-12 19:00', 'μg/m3'], dtype=object)],
 '2022-01-12 19:00')

In [29]:
_data = round(data.groupby(_groupby).mean(),2)
_data

         PM25
county
南投縣     46.20
嘉義市     54.00
嘉義縣     22.50
基隆市      9.00
宜蘭縣      9.00
屏東縣     24.40
彰化縣     17.75
新北市     10.85
新竹市     16.00
新竹縣     11.50
桃園市     11.50
澎湖縣     10.00
臺中市     17.50
臺北市     11.57
臺南市     29.00
臺東縣      7.00
花蓮縣      9.00
苗栗縣     13.75
連江縣     39.00
金門縣     32.00
雲林縣     30.29
高雄市     40.93

In [30]:
a = _data.index
b = _data['PM25']
list(a),list(b)

(['南投縣',
  '嘉義市',
  '嘉義縣',
  '基隆市',
  '宜蘭縣',
  '屏東縣',
  '彰化縣',
  '新北市',
  '新竹市',
  '新竹縣',
  '桃園市',
  '澎湖縣',
  '臺中市',
  '臺北市',
  '臺南市',
  '臺東縣',
  '花蓮縣',
  '苗栗縣',
  '連江縣',
  '金門縣',
  '雲林縣',
  '高雄市'],
 [46.2,
  54.0,
  22.5,
  9.0,
  9.0,
  24.4,
  17.75,
  10.85,
  16.0,
  11.5,
  11.5,
  10.0,
  17.5,
  11.57,
  29.0,
  7.0,
  9.0,
  13.75,
  39.0,
  32.0,
  30.29,
  40.93])

In [32]:
#data.groupby(_groupby).get_group(_groupbycol[0])['PM25'].mean()
_data =pd.DataFrame([round(data.groupby(_groupby).get_group(col)['PM25'].mean(),2) for col in _groupbycol], index=_groupbycol, columns=['PM25'])
_data

      PM25
臺北市  11.57
臺中市  17.50

In [33]:
a = _data.index
b = _data['PM25']
list(a),list(b)

(['臺北市', '臺中市'], [11.57, 17.5])